name: Léon Augusto
bio: '# Hello World #'
picture: 'assets/images/leon_profile.jpg'

url: http://leonaugusto16.github.io/
permalink: /:title/

analytics: 'UA-MYANALYTICS'
facebook: https://www.facebook.com/leon.augusto.7
linkedin: mylinkedin
github: https://github.com/leonaugusto16
email: leonaugusto16@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
